version: '3.8'

services:
  nats:
    image: nats
    ports:
      - 4222:4222

  mysql_db:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser123
      MYSQL_DATABASE: default_db
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root_password_123 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  api_gateway:
    build: ./http-api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    depends_on:
      - users_microservice
      - social_media_microservice
    environment:
      PORT: 3000
      USERS_SERVICE_HOST: users_microservice
      USERS_SERVICE_PORT: 3001
      SOCIAL_MEDIA_SERVICE_HOST: social_media_microservice
      SOCIAL_MEDIA_SERVICE_PORT: 3002

  users_microservice:
    build: ./users-microservice
    ports:
      - "3001:3001"
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    command: npm run start:dev
    depends_on:
      - mysql_db
    environment:
      DATABASE_HOST: mysql_db
      DATABASE_PORT: 3306
      DATABASE_USER: testuser
      DATABASE_PASSWORD: testuser123
      DATABASE_NAME: users_db
      PORT: 3001

  social_media_microservice:
    build: ./social-microservice
    ports:
      - "3002:3002"
    volumes:
      - ./social-microservice/src:/usr/src/app/src
    command: npm run start:dev
    depends_on:
      - mysql_db
    environment:
      DATABASE_HOST: mysql_db
      DATABASE_PORT: 3306
      DATABASE_USER: testuser
      DATABASE_PASSWORD: testuser123
      DATABASE_NAME: social_media_db
      PORT: 3002

volumes:
  db_data:
